name: "Publish Release"
description: "Publish assets and finalize GitHub release"
inputs:
  token:
    description: "GitHub access token"
    required: true
  target:
    description: "The owner/repo GitHub target"
    required: false
  branch:
    description: "The target branch"
    required: false
  release_url:
    description: "The full url to the GitHub release page"
    required: false
  dry_run:
    description: "If set, do not push permanent changes"
    default: "false"
    required: false
  steps_to_skip:
    description: "Comma separated list of steps to skip"
    required: false

outputs:
  release_url:
    description: "The html URL of the GitHub release"
    value: ${{ steps.publish-release.outputs.release_url }}
  pr_url:
    description: "The html URL of the forwardport PR if applicable"
    value: ${{ steps.publish-release.outputs.pr_url }}

runs:
  using: "composite"
  steps:
    - name: install-releaser
      shell: bash -eux {0}
      run: |
        # Install Jupyter Releaser from git unless we are testing Releaser itself
        if ! command -v jupyter-releaser &> /dev/null
        then
            pip install -q git+https://github.com/jupyter-server/jupyter_releaser.git@v1
        fi
    - id: publish-release
      shell: bash -eux {0}
      run: |
        export GITHUB_ACCESS_TOKEN=${{ inputs.token }}
        export RH_REPOSITORY=${{ inputs.target }}
        export RH_DRY_RUN=${{ inputs.dry_run }}
        export RH_RELEASE_URL=${{ inputs.release_url }}
        export RH_STEPS_TO_SKIP=${{ inputs.steps_to_skip }}
        export RH_BRANCH=${{ inputs.branch }}
        python -m jupyter_releaser.actions.publish_release
