name: "Publish Release"
description: "Publish assets and finalize GitHub release"
inputs:
  token:
    description: "GitHub access token"
    required: true
  release_url:
    description: "The full url to the GitHub release page"
    required: true
  dry_run:
    description: "If set, do not push permanent changes"
    default: "false"
    required: false
  steps_to_skip:
    description: Comma separated list of steps to skip
    required: false

outputs:
  release_url:
    description: "The html URL of the GitHub release"
    value: ${{ steps.publish-release.outputs.release_url }}
  pr_url:
    description: "The html URL of the forwardport PR if applicable"
    value: ${{ steps.publish-release.outputs.pr_url }}

runs:
  using: "composite"
  steps:
    - name: install-releaser
      uses: jupyter-server/jupyter_releaser/.github/actions/install-releaser@v1

    - shell: bash
      id: publish-release
      run: |
        set -eux

        # Set up env variables
        export GITHUB_ACCESS_TOKEN=${{ inputs.token }}
        export RH_DRY_RUN=${{ inputs.dry_run }}
        export release_url=${{ inputs.release_url }}
        export RH_STEPS_TO_SKIP=${{ inputs.steps_to_skip }}

        # Publish release
        python -m jupyter_releaser.actions.publish_release
