name: "Install Releaser"
description: "Ensure Releaser is Installed"
runs:
  using: "composite"
  steps:
    - shell: bash
      id: install-releaser
      run: |
        cd "${{ github.action_path }}/../../scripts"
        bash install-releaser.sh
