name: "Check Links"
description: "Run a link check function for a repo"
runs:
  using: "composite"
  steps:
    - name: install-releaser
      shell: bash -eux {0}
      id: install-releaser
      run: |
        # Install Jupyter Releaser from git unless we are testing Releaser itself
        if ! command -v jupyter-releaser &> /dev/null
        then
            pip install -q git+https://github.com/jupyter-server/jupyter_releaser.git@v1
        fi

    - name: Cache checked links
      uses: actions/cache@v2
      with:
        path: ~/.cache/releaser-link-check
        key: ${{ runner.os }}-releaser-linkcheck-${{ hashFiles('**/*.md', '**/*.rst') }}-links
        restore-keys: |
          ${{ runner.os }}-releaser-linkcheck-

    - shell: bash
      id: check-links
      run: |
        set -eux
        python -m jupyter_releaser.actions.check_links
