name: "Check Release"
description: "Run through a dry run release cycle"
inputs:
  token:
    description: "GitHub access token"
    required: true
  version_spec:
    description: "New Version Specifier"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: install-releaser
      uses: ./../install-releaser

    - name: draft-changelog
      uses: ./../draft-changelog
      env:
        RH_IS_CHECK_RELEASE: "true"
      with:
        dry_run: true
        token: ${{ inputs.token }}
        version_spec: ${{ inputs.version_spec }}

    - name: draft-release
      uses: ./../draft-release
      env:
        RH_IS_CHECK_RELEASE: "true"
      with:
        dry_run: true
        token: ${{ inputs.token }}
        version_spec: ${{ inputs.version_spec }}
        release_url: ${{ steps.draft-changelog.outputs.release_url }}

    - name: publish-release
      uses: ./../publish-release
      env:
        RH_IS_CHECK_RELEASE: "true"
      with:
        dry_run: true
        token: ${{ inputs.token }}
        release_url: ${{ steps.draft-changelog.outputs.release_url }}
