name: "Check Release"
description: "Run through a dry run release cycle"
inputs:
  token:
    description: "GitHub access token"
    required: true
  version_spec:
    description: "New Version Specifier"
    required: false
    default: ""
  steps_to_skip:
    description: "Comma separated list of steps to skip"
    required: false
runs:
  using: "composite"
  steps:
    - shell: bash -eux {0}
      id: install-releaser
      run: |
        # Install Jupyter Releaser from git unless we are testing Releaser itself
        if ! command -v jupyter-releaser &> /dev/null
        then
            pip install -q git+https://github.com/jupyter-server/jupyter_releaser.git@v1
        fi

    - id: draft-changelog
      shell: bash -eux {0}
      run: |
        export RH_IS_CHECK_RELEASE="true"
        export GITHUB_ACCESS_TOKEN=${{ inputs.token }}
        export RH_VERSION_SPEC=${{ inputs.version_spec }}
        export RH_STEPS_TO_SKIP=${{ inputs.steps_to_skip }}
        python -m jupyter_releaser.actions.draft_changelog

    - id: draft-release
      shell: bash -eux {0}
      run: |
        export RH_IS_CHECK_RELEASE="true"
        export GITHUB_ACCESS_TOKEN=${{ inputs.token }}
        export RH_RELEASE_URL=${{ steps.draft-changelog.outputs.release_url }}
        export RH_STEPS_TO_SKIP=${{ inputs.steps_to_skip }}
        python -m jupyter_releaser.actions.draft_release

    - id: publish-release
      shell: bash -eux {0}
      run: |
        export RH_IS_CHECK_RELEASE="true"
        export GITHUB_ACCESS_TOKEN=${{ inputs.token }}
        export RH_RELEASE_URL=${{ steps.draft-changelog.outputs.release_url }}
        export RH_STEPS_TO_SKIP=${{ inputs.steps_to_skip }}
        python -m jupyter_releaser.actions.publish_release
