name: "Check Release"
description: "Run through a dry run release cycle"
inputs:
  token:
    description: "GitHub access token"
    required: true
  changelog:
    description: "Changelog file"
    default: "CHANGELOG.md"
    required: false
  version_spec:
    description: "New Version Specifier"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: install-releaser
      uses: jupyter-server/jupyter_releaser/.github/actions/install-releaser@v1

    - name: draft-changelog
      uses: jupyter-server/jupyter_releaser/.github/actions/draft-changelog@v1
      env:
        RH_IS_CHECK_RELEASE: "true"
      with:
        dry_run: true
        token: ${{ inputs.token }}
        changelog: ${{ inputs.changelog }}
        version_spec: ${{ inputs.version_spec }}

    - name: draft-release
      uses: jupyter-server/jupyter_releaser/.github/actions/draft-release@v1
      env:
        RH_IS_CHECK_RELEASE: "true"
      with:
        dry_run: true
        token: ${{ inputs.token }}
        changelog: ${{ inputs.changelog }}
        version_spec: ${{ inputs.version_spec }}

    - name: publish-release
      uses: jupyter-server/jupyter_releaser/.github/actions/publish-release@v1
      env:
        RH_IS_CHECK_RELEASE: "true"
      with:
        dry_run: true
        token: ${{ inputs.token }}
        release_url: ""
