name: "Draft Changelog"
description: "Create an automated changelog entry PR"
inputs:
  token:
    description: "GitHub access token"
    required: true
  target:
    description: "The owner/repo GitHub target"
    required: true
  version_spec:
    description: "New Version Specifier"
    default: "next"
    required: false
  branch:
    description: "The branch to target"
    required: false
  post_version_spec:
    description: "Post Version Specifier"
    required: false
  dry_run:
    description: "If set, do not make a PR"
    default: "false"
    required: false
  since:
    description: "Use PRs with activity since this date or git reference"
    required: false
  since_last_stable:
    description: "Use PRs with activity since the last stable git tag"
    required: false
outputs:
  pr_url:
    description: "The URL of the Changelog Pull Request"
    value: ${{ steps.draft-changelog.outputs.pr_url }}
  release_url:
    description: "The html URL of the draft GitHub release"
    value: ${{ steps.draft-changelog.outputs.release_url }}
runs:
  using: "composite"
  steps:
    - name: install-releaser
      shell: bash -eux {0}
      run: |
        # Install Jupyter Releaser from git unless we are testing Releaser itself
        if ! command -v jupyter-releaser &> /dev/null
        then
            pip install -q git+https://github.com/jupyter-server/jupyter_releaser.git@v1
        fi

    - id: draft-changelog
      shell: bash -eux {0}
      run: |
        export GITHUB_ACCESS_TOKEN=${{ inputs.token }}
        export RH_REPOSITORY=${{ inputs.target }}
        if [ ! -z ${{ inputs.branch }} ]; then
          export RH_BRANCH=${{ inputs.branch }}
        fi
        export RH_VERSION_SPEC=${{ inputs.version_spec }}
        export RH_POST_VERSION_SPEC=${{ inputs.post_version_spec }}
        export RH_DRY_RUN=${{ inputs.dry_run }}
        export RH_SINCE=${{ inputs.since }}
        export RH_SINCE_LAST_STABLE=${{ inputs.since_last_stable }}

        python -m jupyter_releaser.actions.draft_changelog
