name: "Publish Changelog"
description: "Remove silent placeholder entries in the changelog file."
inputs:
  token:
    description: "GitHub access token"
    required: true
  target:
    description: "The owner/repo GitHub target"
    required: true
  branch:
    description: "The branch to target"
    required: false
  dry_run:
    description: "If set, do not make a PR"
    default: "false"
    required: false
outputs:
  pr_url:
    description: "The html URL of the draft GitHub release"
    value: ${{ steps.publish-changelog.outputs.pr_url }}
runs:
  using: "composite"
  steps:
    - name: install-releaser
      shell: bash -eux {0}
      run: |
        # Install Jupyter Releaser from git unless we are testing Releaser itself
        if ! command -v jupyter-releaser &> /dev/null
        then
            pip install -q git+https://github.com/jupyter-server/jupyter_releaser.git@v2
        fi

    - id: publish-changelog
      shell: bash -eux {0}
      run: |
        export GITHUB_ACCESS_TOKEN=${{ inputs.token }}
        export GITHUB_ACTOR=${{ github.triggering_actor }}
        export RH_REPOSITORY=${{ inputs.target }}
        if [ ! -z ${{ inputs.branch }} ]; then
          export RH_BRANCH=${{ inputs.branch }}
        fi
        export RH_DRY_RUN=${{ inputs.dry_run }}

        python -m jupyter_releaser.actions.publish_changelog

    - shell: bash -eux {0}
      run: |
        echo "## Next Step" >> $GITHUB_STEP_SUMMARY
        echo "Merge the changelog update PR: ${{ steps.publish-changelog.outputs.pr_url }}" >> $GITHUB_STEP_SUMMARY
