name: "Finalize Release"
description: "Publish assets and finalize GitHub release"
inputs:
  token:
    description: "GitHub access token"
    required: true
  target:
    description: "The owner/repo GitHub target"
    required: false
  branch:
    description: "The target branch"
    required: false
  release_url:
    description: "The full url to the GitHub release page"
    required: false
  dry_run:
    description: "If set, do not push permanent changes"
    default: "false"
    required: false
  steps_to_skip:
    description: "Comma separated list of steps to skip"
    required: false

outputs:
  release_url:
    description: "The html URL of the GitHub release"
    value: ${{ steps.finalize-release.outputs.release_url }}
  pr_url:
    description: "The html URL of the forwardport PR if applicable"
    value: ${{ steps.finalize-release.outputs.pr_url }}

runs:
  using: "composite"
  steps:
    - name: install-releaser
      shell: bash -eux {0}
      run: |
        # Install Jupyter Releaser from git unless we are testing Releaser itself
        if ! command -v jupyter-releaser &> /dev/null
        then
            pip install -q git+https://github.com/jupyter-server/jupyter_releaser.git@v2
        fi

    - id: finalize-release
      shell: bash -eux {0}
      run: |
        export GITHUB_ACCESS_TOKEN=${{ inputs.token }}
        export GITHUB_ACTOR=${{ github.triggering_actor }}
        export RH_REPOSITORY=${{ inputs.target }}
        export RH_DRY_RUN=${{ inputs.dry_run }}
        export RH_RELEASE_URL=${{ inputs.release_url }}
        export RH_STEPS_TO_SKIP=${{ inputs.steps_to_skip }}
        export RH_BRANCH=${{ inputs.branch }}
        python -m jupyter_releaser.actions.finalize_release

    - if: ${{ success() }}
      shell: bash -eux {0}
      run: |
        echo "## Next Step" >> $GITHUB_STEP_SUMMARY
        echo "Verify the final release" >> $GITHUB_STEP_SUMMARY
        echo ${{ steps.finalize-release.outputs.release_url }} >> $GITHUB_STEP_SUMMARY
        if [ ! -z "${{ steps.finalize-release.outputs.pr_url }}" ]; then
           echo "Merge the forwardport PR"
           echo ${{ steps.finalize-release.outputs.pr_url }}
           echo "Merge the forwardport PR" >> $GITHUB_STEP_SUMMARY
           echo ${{ steps.finalize-release.outputs.pr_url }} >> $GITHUB_STEP_SUMMARY
        fi

    - if: ${{ failure() }}
      shell: bash -eux {0}
      run: |
        echo "## Failure Message" >> $GITHUB_STEP_SUMMARY
        echo ":x: Failed to Publish the Draft Release Url:" >> $GITHUB_STEP_SUMMARY
        echo ${{ inputs.release_url }} >> $GITHUB_STEP_SUMMARY
